--SECURITY MODULES
    --DROP SECURITY TABLES
    USE [BDCABANA_V2]
        DROP TABLE [ROLES]
        DROP TABLE [MODULES]
        DROP TABLE [PERMISIONS]
        DROP TABLE [USERS]
        DROP TABLE [ROLES_PERMISIONS]
        DROP TABLE [USERS_ROLES]
    GO
    --DROP SECURITY TABLES
    USE [BDCABANA_V2]
        DROP FROM [MODULES] WHERE IDPARENTMODULE = 6
        DROP FROM [ROLES] WHERE IDROLE = '"++"'
        DROP FROM [PERMISIONS] WHERE IDPERMISION = '"++"'
        DROP FROM [USERS] WHERE USERNAME = '"++"'
        DROP FROM [ROLES_PERMISIONS] WHERE IDROLE = '"++"' AND IDPERMISION = '"++"'
        DROP FROM [USERS_ROLES] WHERE USERNAME = "++" AND IDROLE = "+"
    GO
--MAINTENANCE MODULES
    --DROP MAINTENANCE TABLES
    USE [BDCABANA_V2]
        DROP TABLE [AREAS]
        DROP TABLE [BRANCHES]
        DROP TABLE [CATEGORIES]
        DROP TABLE [MENUS]
        DROP TABLE [PRODUCTS]
        DROP TABLE [STATUS]
        DROP TABLE [TABLES]
    GO
    --DROP MAINTENANCE TABLES
    USE [BDCABANA_V2]
        DROP FROM [AREAS] WHERE = "++"
        DROP FROM [BRANCHES] WHERE = "++"
        DROP FROM [CATEGORIES] WHERE = "++"
        DROP FROM [MENUS] WHERE = "++"
        DROP FROM [PRODUCTS] WHERE = "++"
        DROP FROM [STATUS] WHERE = "++"
        DROP FROM [TABLES] WHERE = "++"
    GO
--PROCESS MODULES
    --DROP PROCESS TABLES
        DROP TABLE [CLIENTS]
        DROP TABLE [VENDORS]
        DROP TABLE [WORKERS]
    --DROP PROCESS TABLES
        DROP FROM [CLIENTS] WHERE = "++"
        DROP FROM [VENDORS] WHERE = "++"
        DROP FROM [WORKERS] WHERE = "++"
--REPORT MODULES
    --DROP REPORT TABLES
    --DROP REPORT TABLES
--TRANSACTION MODULES
    --DROP TRANSACTION TABLES
        DROP TABLE [ORDERS]
        DROP TABLE [ORDERDETAILS]
        DROP TABLE [PURCHASES]
        DROP TABLE [PURCHASEDETAILS]
    --DROP TRANSACTION TABLES
        DELETE FROM [ORDERS] 
        DELETE FROM [ORDERDETAILS] 
        DELETE FROM [PURCHASES]
        DELETE FROM [PURCHASEDETAILS]


